---
language: ruby
bundler_args: --without system_tests development
script: "bundle install && bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
cache: bundler
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4"
notifications:
  email:
    - luc@raeskin.eu